(function(){
'use strict';
const SUPABASE_URL='https://qbijrkdlaguwlvriaiky.supabase.co';
const SUPABASE_KEY='sb_publishable_CS7wauVRlHpbsdjJFdWl1g_cNdjogHJ';
const ADMIN='meherulhassan62@gmail.com';
function escapeHtml(value){return String(value).replace(/[&<>\"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;', '\"':'&quot;',"'":'&#39;'}[c];});}
function loadSupport(){if(document.querySelector('script[data-shrtigo-support-loader]'))return;const script=document.createElement('script');script.src='/support-loader.js';script.defer=true;script.dataset.shrtigoSupportLoader='1';document.head.appendChild(script);}
function boot(){
 if(!window.supabase||!window.supabase.createClient)return;
 const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
 const style=document.createElement('style');style.id='shrtigo-profile-style';style.textContent=`
 .sh-profile{position:relative!important;display:flex!important;align-items:center!important;margin-left:12px!important;flex:0 0 auto!important;z-index:120!important}
 .sh-profile-btn{display:inline-flex;align-items:center;justify-content:center;gap:7px;min-height:42px;padding:10px 15px;border:1px solid #d8e2f0;border-radius:13px;background:#fff;color:#172033;font:inherit;font-size:13px;font-weight:850;cursor:pointer;box-shadow:0 7px 20px rgba(23,32,51,.06);white-space:nowrap}
 .sh-profile-menu{position:absolute!important;right:0!important;top:calc(100% + 10px)!important;width:280px!important;background:#fff!important;border:1px solid #e1e8f2!important;border-radius:18px!important;padding:12px!important;box-shadow:0 22px 55px rgba(23,32,51,.16)!important;z-index:99999!important}
 .sh-profile-menu[hidden]{display:none!important}.sh-profile-menu a,.sh-profile-menu button{display:flex;align-items:center;gap:9px;width:100%;min-height:42px;text-align:left;padding:11px 12px;border:0;background:transparent;color:#172033;text-decoration:none;font:inherit;font-size:14px;font-weight:800;border-radius:10px;cursor:pointer}.sh-profile-menu a:hover,.sh-profile-menu button:hover{background:#f1f5ff;color:#2563eb}.sh-profile-head{padding:7px 10px 10px}.sh-profile-name{font-size:15px;font-weight:900;color:#172033;overflow-wrap:anywhere}.sh-profile-email{margin-top:7px;font-size:12px;line-height:1.5;color:#687386;overflow-wrap:anywhere}.sh-profile-menu hr{border:0;border-top:1px solid #edf1f6;margin:4px 0 7px}
 @media(max-width:800px){.sh-profile{margin-left:auto!important}.sh-profile-menu{position:fixed!important;right:14px!important;top:70px!important;width:min(280px,calc(100vw - 28px))!important}}
 `;document.head.appendChild(style);
 function addProfile(user){const nav=document.querySelector('header .nav');if(!nav||document.getElementById('shProfile'))return;const email=String(user.email||'');const name=user.user_metadata?.full_name||user.user_metadata?.name||email.split('@')[0]||'User';const wrap=document.createElement('div');wrap.id='shProfile';wrap.className='sh-profile';wrap.innerHTML='<button type="button" class="sh-profile-btn" id="shProfileBtn">👤 Profile</button><div class="sh-profile-menu" id="shProfileMenu" hidden><div class="sh-profile-head"><div class="sh-profile-name">'+escapeHtml(name)+'</div><div class="sh-profile-email">'+escapeHtml(email)+'</div></div><hr><a href="/dashboard.html">📊 Dashboard</a><a href="/subscription.html">💳 Subscription</a>'+(email.toLowerCase()===ADMIN?'<a href="/admin.html">🛠 Admin Panel</a><a href="/support-admin.html">💬 Support Inbox</a>':'')+'<button type="button" id="shLogout">↪ Log out</button></div>';nav.appendChild(wrap);const btn=wrap.querySelector('#shProfileBtn'),menu=wrap.querySelector('#shProfileMenu');btn.addEventListener('click',function(e){e.stopPropagation();menu.hidden=!menu.hidden;});document.addEventListener('click',function(e){if(!wrap.contains(e.target))menu.hidden=true;});wrap.querySelector('#shLogout').addEventListener('click',async function(){await sb.auth.signOut();try{await fetch('/api/auth/session',{method:'DELETE'});}catch(error){}location.replace('/central-login.html?next=%2Findex.html');});}
 sb.auth.getSession().then(function(result){if(result&&result.data&&result.data.session)addProfile(result.data.session.user);});
}
function loadSupabase(){if(window.supabase&&window.supabase.createClient){boot();loadSupport();return;}const script=document.createElement('script');script.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';script.onload=function(){boot();loadSupport();};document.head.appendChild(script);}loadSupabase();
})();