create table if not exists public.links (
  id bigint generated by default as identity primary key,
  code text not null,
  domain text,
  url text not null,
  image_url text,
  youtube_url text,
  clicks bigint not null default 0,
  created_at timestamptz not null default now()
);

alter table public.links add column if not exists youtube_url text;
alter table public.links add column if not exists link_mode text not null default 'advanced';
alter table public.links add column if not exists deleted_at timestamptz;
alter table public.links add column if not exists owner_token text;
alter table public.links add column if not exists user_id uuid;

create index if not exists links_code_idx on public.links(code);
create unique index if not exists links_domain_code_uidx on public.links(domain, code);
create index if not exists links_domain_code_idx on public.links(domain, code);
create index if not exists links_user_deleted_idx on public.links(user_id, deleted_at, created_at);
create index if not exists links_owner_token_idx on public.links(owner_token, deleted_at, created_at);

create table if not exists public.analytics_visitors (
  id bigint generated by default as identity primary key,
  code text not null,
  visitor_id text not null,
  last_seen timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (code, visitor_id)
);

create index if not exists analytics_visitors_code_idx on public.analytics_visitors(code);
create index if not exists analytics_visitors_last_seen_idx on public.analytics_visitors(last_seen);

create table if not exists public.subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  plan text not null,
  link_limit integer not null,
  status text not null default 'pending',
  payment_method text,
  transaction_id text,
  expires_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists subscriptions_user_status_idx on public.subscriptions(user_id, status, expires_at);

insert into storage.buckets (id, name, public)
values ('short-images', 'short-images', true)
on conflict (id) do update set public = true;

-- The Vercel API uses the Supabase service-role key.
-- Keep SUPABASE_SERVICE_ROLE_KEY secret and never put it in index.html.


-- Hot-path resolver for production redirect traffic.
-- Codes are compact (typically 4 characters) and may be reused on different
-- Shrtigo domains. Resolution therefore uses both host/domain and code.
create or replace function public.shrtigo_resolve_and_consume(p_code text, p_domain text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $function$
declare
  v_link public.links%rowtype;
  v_sub_id uuid;
  v_consumed boolean := true;
  v_domain text := lower(trim(regexp_replace(coalesce(p_domain,''), '^www\.', '')));
begin
  select * into v_link
  from public.links
  where code = p_code
    and (lower(coalesce(domain,'')) = v_domain or domain is null)
  order by (domain is null)
  limit 1;

  if not found then
    return jsonb_build_object('found', false);
  end if;

  if v_link.user_id is not null then
    select s.id into v_sub_id
    from public.subscriptions s
    where s.user_id = v_link.user_id
      and s.status = 'active'
      and (s.ends_at is null or s.ends_at > now())
    order by s.ends_at desc nulls last
    limit 1;

    if v_sub_id is not null then
      update public.subscriptions
      set clicks_used = coalesce(clicks_used, 0) + 1,
          updated_at = now()
      where id = v_sub_id
        and (click_limit is null or coalesce(clicks_used, 0) < click_limit)
      returning true into v_consumed;

      if not coalesce(v_consumed, false) then
        return jsonb_build_object('found', true, 'consumed', false, 'code', v_link.code, 'user_id', v_link.user_id);
      end if;
    end if;
  end if;

  update public.links
  set clicks = coalesce(clicks, 0) + 1
  where id = v_link.id;

  return jsonb_build_object(
    'found', true,
    'consumed', true,
    'code', v_link.code,
    'domain', v_link.domain,
    'url', v_link.url,
    'image_url', v_link.image_url,
    'youtube_url', v_link.youtube_url,
    'clicks', coalesce(v_link.clicks, 0) + 1,
    'link_mode', v_link.link_mode,
    'user_id', v_link.user_id
  );
end;
$function$;

revoke execute on function public.shrtigo_resolve_and_consume(text,text) from public, anon, authenticated;
grant execute on function public.shrtigo_resolve_and_consume(text,text) to service_role;

-- Domain selection is locked to the active plan until the user changes plans.
alter table if exists public.user_domain_settings add column if not exists selection_plan text;


-- Support chat access uses the logged-in user's JWT instead of a Vercel service-role secret.
-- This keeps the service-role key out of Vercel for the Support Inbox.

create table if not exists public.support_messages (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  sender_role text not null check (sender_role in ('user', 'admin')),
  message text not null check (char_length(trim(message)) between 1 and 2000),
  created_at timestamptz not null default now(),
  read_at timestamptz
);

alter table public.support_messages enable row level security;

drop policy if exists "support_messages_select_own_or_admin" on public.support_messages;
drop policy if exists "support_messages_insert_own_or_admin" on public.support_messages;
drop policy if exists "support_messages_update_own_admin_messages" on public.support_messages;

create policy "support_messages_select_own_or_admin"
on public.support_messages
for select
to authenticated
using (
  user_id = auth.uid()
  or lower(coalesce(auth.jwt()->>'email','')) = 'meherulhassan62@gmail.com'
);

create policy "support_messages_insert_own_or_admin"
on public.support_messages
for insert
to authenticated
with check (
  (user_id = auth.uid() and sender_role = 'user')
  or (
    lower(coalesce(auth.jwt()->>'email','')) = 'meherulhassan62@gmail.com'
    and sender_role = 'admin'
  )
);

create policy "support_messages_update_own_admin_messages"
on public.support_messages
for update
to authenticated
using (
  user_id = auth.uid() and sender_role = 'admin'
)
with check (
  user_id = auth.uid() and sender_role = 'admin'
);

create or replace function public.shrtigo_admin_broadcast_support(p_admin_email text, p_message text)
returns integer
language plpgsql
security definer
set search_path to ''
as $function$
declare
  inserted_count integer;
  caller_email text;
begin
  caller_email := lower(trim(coalesce(auth.jwt()->>'email','')));

  if caller_email <> 'meherulhassan62@gmail.com'
     or lower(trim(coalesce(p_admin_email, ''))) <> 'meherulhassan62@gmail.com' then
    raise exception 'Not authorized';
  end if;

  if char_length(trim(coalesce(p_message, ''))) < 1 or char_length(p_message) > 2000 then
    raise exception 'Message must be between 1 and 2000 characters.';
  end if;

  insert into public.support_messages (user_id, sender_role, message)
  select u.id, 'admin', trim(p_message)
  from auth.users u
  where lower(coalesce(u.email, '')) <> 'meherulhassan62@gmail.com';

  get diagnostics inserted_count = row_count;
  return inserted_count;
end;
$function$;

revoke all on function public.shrtigo_admin_broadcast_support(text, text) from public;
grant execute on function public.shrtigo_admin_broadcast_support(text, text) to authenticated;
