create table if not exists public.links (
  id bigint generated by default as identity primary key,
  code text not null unique,
  url text not null,
  image_url text,
  youtube_url text,
  clicks bigint not null default 0,
  created_at timestamptz not null default now()
);

alter table public.links add column if not exists youtube_url text;
alter table public.links add column if not exists link_mode text not null default 'advanced';

create index if not exists links_code_idx on public.links(code);

create table if not exists public.analytics_visitors (
  id bigint generated by default as identity primary key,
  code text not null,
  visitor_id text not null,
  last_seen timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (code, visitor_id)
);

create index if not exists analytics_visitors_code_idx on public.analytics_visitors(code);
create index if not exists analytics_visitors_last_seen_idx on public.analytics_visitors(last_seen);

insert into storage.buckets (id, name, public)
values ('short-images', 'short-images', true)
on conflict (id) do update set public = true;

-- The Vercel API uses the Supabase service-role key.
-- Keep SUPABASE_SERVICE_ROLE_KEY secret and never put it in index.html.
